confusing posts object
I'm trying to follow the tuts, and constantly returning an error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'EditPost'
===
this is happened because posts in the first code block different from the second block, so, to avoid the confusion, I'm adding this to the second block...

from wordpress_xmlrpc.methods import posts